version: '3'
services:

  nginx:
    build: 
      context: .docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    networks:
      - app
      - php
    depends_on:
      - php
      - db

  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - php
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=app_db

  db:
      image: mysql:8.0.30
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: fadakar
        MYSQL_PASSWORD: fadakar
        MYSQL_DATABASE: app_db
      volumes:
        - my-db:/var/lib/mysql
      networks: 
        - db

volumes:
  my-db:
    driver: local

networks:
  app:
    driver: bridge
  php:
  db: