version: '3'
services:

  nginx:
    build: 
      context: .docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

volumes:
  mysqldata:
    driver: local

networks:
  app-network:
    driver: bridge